version: '3.9'

services:
  # ASP.NET Core API service
  api:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    restart: unless-stopped
    volumes:
    - ./CloudSystem/CloudSystem:/CloudSystem
    - ./CloudSystem/CloudSystem.sln:/CloudSystem.sln
    ports:
      - "5000:80"  # Map host port 5000 to container port 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command: dotnet run --project CloudSystem/CloudSystem.csproj