version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - cloudStorage:/data
      - ./Certificates/mycert.pfx:/certificates/mycert.pfx
    restart: unless-stopped
volumes:
  cloudStorage: